[options]
; Booleen pour activer le thème sombre
mode_sombre=false

[statistiques]
; Temps total passé à résoudre des grilles
temps_total=14400
; Difficulté maximale atteinte et résolue (1 = Facile, 2 = Moyenne, 3 = Difficile)
difficulte_max=2
; Score maximal atteint
score_max=52420
; Ratio des parties réussies sur celles tentées/entamées
ratio_parties=0.75

[aventure]
; Le dernier niveau complété par l'utilisateur en mode "Aventure"
; Par exemple, un champ `progression=0` veut dire que le mode Aventure
; a été ré-initialisé ou que la personne ne l'a jamais commencé.
progression=3